/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advanced.avocado.trainer;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class AppTest
{
    // @Test
    // void appHasAGreeting()
    // {
    // Trainer classUnderTest = new Trainer();
    // assertNotNull( classUnderTest.getGreeting(), "app should have a greeting" );
    // }
}
